# Generated by Django 4.2.10 on 2024-05-11 10:15

from django.db import migrations, models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
                migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('pdf_file', models.FileField(upload_to='reports/')),
                ('upload_time', models.CharField(default='', max_length=200)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.semester')),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='upload_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
