# Generated by Django 4.2.10 on 2024-04-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_student_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
    ]
