# Generated by Django 4.2.10 on 2024-04-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_student_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='priority_level',
            field=models.IntegerField(default=0),
        ),
    ]
