# Generated by Django 4.2.10 on 2024-04-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_student_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
