# Generated by Django 4.2.10 on 2024-04-06 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='priority_level',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_title', models.CharField(default='', max_length=200)),
                ('degree_abbbrev', models.CharField(default='', max_length=200)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.college')),
            ],
        ),
    ]
