# Generated by Django 4.2.10 on 2024-04-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_student_priority_level_degreeprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='deg_prog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.degreeprogram'),
        ),
    ]
