# Generated by Django 4.2.10 on 2024-04-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_student_deg_prog'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='first_prio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='fourth_prio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='second_prio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='third_prio',
            field=models.IntegerField(default=0),
        ),
    ]
